### ISSUE TITLE
Fetch wasm file failed in local file (Manifest V3)

### ISSUE THREAD

**Issue by Folyd** [huhu/rust-search-extension#189]
```
macro-railroad-wasm.js:418          GET chrome-extension://ennpfpdlaclocpomkiablnmbppdnlhoh/wasm/macro-railroad.wasm net::ERR_BLOCKED_BY_CLIENT
init @ macro-railroad-wasm.js:418
load @ macro-railroad.js:11
(anonymous) @ macro-railroad.js:2
macro-railroad-wasm.js:418          Uncaught (in promise) TypeError: Failed to fetch
    at init (macro-railroad-wasm.js:418:17)
    at load (macro-railroad.js:11:11)
    at HTMLDocument.<anonymous> (macro-railroad.js:2:11)
```

**Comment by Folyd** [comment]
Close this. Since we don't need `file:///*` anymore. See https://github.com/huhu/rust-search-extension/commit/05d0760e68520d23afb8aa296f7016ef027148e8.
