### ISSUE TITLE
search doesn't work sometimes

### ISSUE THREAD

**Issue by XyLyXyRR** [huhu/rust-search-extension#244]
search doesn't work sometimes

## Information
- Chromium Version 111.0.5563.146 (Official Build) Arch Linux (64-bit)
- Rust Search Extension 1.10.0

## logs
```log
base.js:505 Uncaught (in promise) TypeError: result.item.path.toLowerCase is not a function
    at SingleCrateDocSearch.sortResults (base.js:505:41)
    at SingleCrateDocSearch.execQuery (base.js:397:21)
    at SingleCrateDocSearch.search (base.js:71:21)
    at CrateDocSearch.searchAll (crate-doc.js:80:38)
    at async QueryEvent.onSearch (main.js:204:20)
    at async QueryEvent.performSearch (query-event.js:34:22)
    at async Omnibox.performSearch (omnibox.js:200:32)
    at async omnibox.js:81:27
sortResults @ base.js:505
execQuery @ base.js:397
search @ base.js:71
searchAll @ crate-doc.js:80
await in searchAll (async)
(anonymous) @ extensions::omnibox:121
```

**Comment by Folyd** [comment]
I found the PR with the breaking change:  https://github.com/rust-lang/rust/pull/107629
